- name: Mount and configure Aegis Secure Key
  hosts: miners
  become: yes
  become_user: rp
  vars:
    data_dir: /home/rp/.rocketpool/data
    tmp_dir: /home/rp/.rocketpool/tmp
    secure_key_bsf: /dev/sda1
  tasks:
    - name: Mount the Secure Key
      block:
        - name: Get list of mounted filesystems
          set_fact:
            mount_names: "{{ ansible_mounts | map(attribute='mount') | list}}"
        - name: Abort if Secure Key already mounted
          fail:
            msg: "Error!  Secure Key is already mounted at '{{ data_dir }}'."
          when: data_dir in mount_names
  
        - name: Check that Secure Key is inserted and unlocked
          stat:
            path: '{{ secure_key_bsf }}'
          register: skbf
        - name: Fail if block special file {{ secure_key_bsf }} does not exist
          fail:
            msg: "Error!  Secure Key must be inserted and unlocked."
          when: skbf.stat.isblk is not defined or skbf.stat.isblk != true
      become: yes
      become_user: root

    - name: Stop Rocket Pool service
      shell: ~/bin/rocketpool service stop -y
    - name: Mount the Secure Key
      block:
        - name: Move {{ data_dir }} to {{ tmp_dir }}
          shell: mv {{ data_dir }} {{ tmp_dir }}
        - name: Create {{ data_dir }} directory
          file:
            path: '{{ data_dir }}'
            state: directory
            mode: '0775'
        - name: Mount {{ secure_key_bsf }} as {{ data_dir }} 
          ansible.posix.mount:
            path: '{{ data_dir }}'
            src: '{{ secure_key_bsf }}'
            fstype: ext4
            state: mounted
        - name: Copy {{ tmp_dir }}/* to {{ data_dir }}
          shell: cp -pr {{ tmp_dir }}/* {{ data_dir }}
        - name: Delete {{ tmp_dir }} 
          file:
            path: '{{ tmp_dir }}'
            state: absent
      become: yes
      become_user: root
    - name: Start Rocket Pool service
      shell: ~/bin/rocketpool service start